### ISSUE TITLE
Map is sideways, but when explicitly stating x and y, it goes blank.

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoplot#17]
![image](https://user-images.githubusercontent.com/15331990/40881907-8e4f0090-6687-11e8-8504-e9c60a6135b2.png)
import os
import xarray as xr
import holoplot.xarray

os.system('wget http://ftp.cpc.ncep.noaa.gov/NMME/realtime_anom/NCAR_CCSM4/2018050800/NCAR_CCSM4.tmpsfc.201805.anom.nc')

ds = xr.open_dataset('NCAR_CCSM4.tmpsfc.201805.anom.nc', decode_cf=False)

ds.fcst.isel(ensmem=0, target=0).plot()

ds.fcst.isel(ensmem=0, target=0).plot(x='lon', y='lat')

**Comment by philippjfr** [comment]
Seems to already be fixed on master.

**Comment by philippjfr** [comment]
Actually fixed in https://github.com/pyviz/holoplot/issues/17, i.e. not on master yet.
