### ISSUE TITLE
groupby plots doesn't adhere to framewise

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoplot#18]
When I do something like

```
%%opts BoxWhisker {-framewise}

from bokeh.sampledata.autompg import autompg as df

title = "MPG by Cylinders and Data Source, Colored by Cylinders"
boxwhisker = hv.BoxWhisker(df, ['cyl', 'origin'], 'mpg', label=title)

df.plot.box('mpg', 'origin', groupby='yr')
```

the ylimits do not stay consistent across frames.
![image](https://user-images.githubusercontent.com/15331990/40883016-3ad5a0ba-66a8-11e8-8aa2-9cbc7660fcd7.png)
![image](https://user-images.githubusercontent.com/15331990/40883017-43d425ec-66a8-11e8-8106-8ef45ce4b698.png)

Works with HoloViews `dataset.to.box` syntax though
```
%%opts BoxWhisker {-framewise}

from bokeh.sampledata.autompg import autompg as df

title = "MPG by Cylinders and Data Source, Colored by Cylinders"
boxwhisker = hv.BoxWhisker(df, ['cyl', 'origin'], 'mpg', label=title)

hv.Dataset(df).to.box('origin', 'mpg', groupby='yr')
```

**Comment by philippjfr** [comment]
The difference here is that holoplot returns a DynamicMap by default which does not support disabling framewise normalization because it would otherwise have to evaluate the entire parameter space.

**Comment by jbednar** [comment]
Shouldn't setting -framewise raise an error on a DynamicMap if the limits are not set some other way?

**Comment by philippjfr** [comment]
I agree we should probably do something here but warning is problematic because -framewise is the default.

**Comment by jbednar** [comment]
Ooh, thats tricky!  Can we somehow make +framewise the default for DynamicMap, and then make it warn if someone tries to change it?
