### ISSUE TITLE
Request: changing .holoplot to .hplot or .hp

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoplot#24]
To me, typing holoplot in its entirety can be a bit tedious.

**Comment by philippjfr** [comment]
There was a fair bit discussion about this, personally I'd be okay with ``.hvplot`` but that's only minimally more convenient. ``.hp`` or ``.hv`` are too short to be considered, as they would likely clash with variable names. ``.hplot`` I don't like much.

The one reason I would consider switching back to ``.hvplot`` is that we could potentially offer an ``.gvplot`` for geoviews based plotting, but that could easily become ``.geoplot``. So on the whole I'm going to close this.

In the long run we hope to integrate properly with the upstream libraries and are pushing for pandas to add a mechanism for replacing the engine for ``.plot`` which xarray could then adopt as well. If you really want to make things more convenient for yourself you can use ``holoplot.patch('pandas', 'hp')`` to patch it with whatever custom abbreviation you desire.
