### ISSUE TITLE
Projections do not work with holoplot

### ISSUE THREAD

**Issue by ahuang11** [pyviz/holoplot#26]
`obs_ds.holoplot.image('lon', 'lat').options(projection=crs.Robinson())`

**Comment by ahuang11** [comment]
Nevermind, had to specify the initial CRS.
```
obs_ds.holoplot.image(x='lon', y='lat', z='air', groupby='time', crs=crs.PlateCarree()).options(projection=crs.Robinson())
```

**Comment by philippjfr** [comment]
```python
obs_ds.holoplot.image(x='lon', y='lat', z='air', groupby='time', crs=crs.PlateCarree(), projection=crs.Robinson())
```

That's also valid.

**Comment by philippjfr** [comment]
``geo=True`` as an alias for ``crs=crs.PlateCarree()``?

**Comment by jbednar** [comment]
Where it's a no-op when combined with an explicit crs like `crs=crs.Robinsion()`, i.e. it simply makes `crs` *default* to PlateCarree? 

I guess the alternative is `obs_ds.geoplot.image(...)`, which seems problematic due to adding another monkeypatching, and won't work when `.plot()` can be overridden.

I have no preference between `geo=True` and `lonlat=True`.

**Comment by philippjfr** [comment]
>I have no preference between geo=True and lonlat=True.

``lonlat=True`` would be invalid when an explicit ``crs`` is defined so I think I prefer geo. Will push that up in 5 minutes. The geographic PR is almost ready, now also has geopandas support.

**Comment by jbednar** [comment]
Right; `lonlat` would have to be an error when combined with `crs=`; it's explicitly declaring PlateCarree rather than only implicitly setting such a default as `geo=True` does when combined with failing to set a `crs=`.  As you wish!

**Comment by philippjfr** [comment]
Now implemented in https://github.com/pyviz/holoplot/pull/21.

``geo`` is set to true if any of the following keywords are used: ``geo``, ``crs``, ``projection``, ``global_extent``

**Comment by jbednar** [comment]
Sounds good, thanks!
