### ISSUE TITLE
trying holoplot-0.0.4 and pandas-0.23.0 under jupyterlab

### ISSUE THREAD

**Issue by stonebig** [pyviz/holoplot#30]
I get an error trying introduction.ipynb, did I miss something ?

````
import holoplot.pandas
df.holoplot()
````

````
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5a136e144f5a> in <module>()
      1 import holoplot.pandas
      2 
----> 3 df.holoplot()

C:\WinP\bd36\buQt5\winp32-3.6.x.1\python-3.6.5\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   4370             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   4371                 return self[name]
-> 4372             return object.__getattribute__(self, name)
   4373 
   4374     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'holoplot'
````

**Comment by philippjfr** [comment]
>all example with df.holoplot do fail ... is this a pandas-0.23 incompatibility ?

I'll have to double check but that's definitely very odd.

**Comment by philippjfr** [comment]
Actually, I'm guessing you installed the current conda/pip release? I only renamed it from ``.plot`` to ``.holoplot`` very recently. There will be a new release by Monday.

**Comment by stonebig** [comment]
ok, ... I'll get the github master, so.

**Comment by stonebig** [comment]
after resolving this, I fall on an series of bad Intake https://github.com/ContinuumIO/intake/issues/107

is the example `Subplots.ipynb` supposed to work under "not-conda" ?

**Comment by philippjfr** [comment]
All the documentation is built on every merge to master so it absolutely should work. You have to make you install the relevant data packages, which are defined in setup.py and the environment.yml.
